version: "3.9"
services:
  rostorch:
    image: e657577afeae
    privileged: true
    tty: true
    network_mode: host
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DOMAIN_ID=5
    # command: bash /docker-volume/install-script.sh
    volumes:
      - /dev:/dev
      - /mnt/SDcard/master-thesis/docker-volume/:/docker-volume
      - /mnt/SDcard/master-thesis/jetson-inference/data:/jetson-inference/data # for models and images
      - /mnt/SDcard/master-thesis/jetson-inference/images:/jetson-inference/images # to save images
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  realsense_ros2:
    network_mode: host
    extends:
      file: realsense-ros2-docker/docker/docker-compose.yml
      service: realsense_ros2
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DOMAIN_ID=5
    command: bash -c "source /opt/ros/humble/setup.bash && source install/setup.bash && ros2 launch realsense2_camera rs_launch.py align_depth.enable:=true enable_color:=true"
    
    runtime: nvidia
  # jetson-inference:
  #   build:
  #     context: jetson-inference
  #     dockerfile: Dockerfile
  #     #target: librealsense
  #   tty: true
  #   environment:
  #     - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
  #   volumes:
  #     - /dev:/dev

