version: '3'

services:

  mir-driver:
    build:
      context: ./mir-driver
      dockerfile: mir-driver.dockerfile
    # pid: container:demo_intermediary_1

    environment:
    - "ROS_MASTER_URI=http://localhost:11311"
    #   - /etc/timezone:/etc/timezone:ro
    #   - /etc/localtime:/etc/localtime:ro
    # volumes:
    #   - /dev/shm:/dev/shm
    # volumes:
    #   # - /home/tristan/repositories/master-thesis/ros2_ws/src/context_aware_navigation/launch/mir_launch.py:/ws/src/mir_robot/mir_driver/launch/mir_launch.py
    #   - /home/tristan/repositories/master-thesis/ros2_ws/src/context_aware_navigation/scripts/mir_bridge.py:/ws/src/mir_robot/mir_driver/nodes/mir_bridge.py
    # command: bash -l -c "tail -f /dev/null" # source devel/setup.bash && roslaunch mir_driver mir.launch" #tail -f /dev/null" #rm -rf /build /install /devel && catkin build && source devel/setup.bash && 
  # ur-driver:
  #   build:
  #     context: ./ur5-driver
  #     dockerfile: ur5-driver.dockerfile

  ros1-bridge:
    # build:
    #   context: ./parameter_bridge
    #   dockerfile: parameter_bridge.dockerfile
    image: ros:foxy-ros1-bridge
    #   - /home/tristan/repositories/aau_littlehelper_docker/docker/parameter_bridge/bridge.yaml:/bridge.yaml
    environment:
      - "ROS_HOSTNAME=ros1-bridge"
      - "ROS_MASTER_URI=http://mir-driver:11311"
      # - "RMW_IMPLEMENTATION=rmw_cyclonedds_cpp"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: bash -l -c "ros2 run ros1_bridge dynamic_bridge" #parameter_bridge tail -f /dev/null #
  # visualizer:
  #   build:
  #     context: ./visualizer
  #     dockerfile: visualizer.dockerfile
    ports:
      - "80:80"
